application:
  name: Yuque-Blog

# TODO FOR TEST
yuque:
  username: iron-man
  authToken:

spring:
  thymeleaf:
    cache: false

forest:
  ## 日志总开关，打开/关闭Forest请求/响应日志（默认为 true）
  log-enabled: true
  ## 打开/关闭Forest请求日志（默认为 true）
  log-request: true
  ## 打开/关闭Forest响应状态日志（默认为 true）
  log-response-status: true
  ## 打开/关闭Forest响应内容日志（默认为 false）
  log-response-content: true